proton: ServiceSpec
pipeline:
  service_dir: "ecs-static-website"
  dockerfile: "Dockerfile"
instances:
- name: "production-website"
  environment: "fargate-env-prod"
  spec:
    port: 80
    desired_count: 2
    task_size: "medium"
    subnet_type: "public"
    loadbalancer_type: "application"
