proton: ServiceSpec
pipeline:
  service_dir: "ecs-static-website"
  dockerfile: "Dockerfile"
  unit_test_command: "echo 'add your unit test command here'"
instances:
- name: "production-website"
  environment: "fargate-prod-env"
  spec:
    port: 80
    desired_count: 1
    task_size: "medium"
    subnet_type: "public"
    loadbalancer_type: "application"
    image: "396367555832.dkr.ecr.ap-northeast-1.amazonaws.com/awsproton-pipeline-fargate-web-svc-cloudformation-yaml-bzdbjxyovkrrxmz-ecrrepo-5avw9ate0vzn:2"
    backendurl: "backend-svc-inst.backend-svc.fargate-env.local:80"
